[package]
name = "tower_defense_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
bevy_egui = "0.20.3"
hexx = "0.6.0"
crossbeam-channel = "0.5"
rand = "0.8.5"
